apiVersion: v1
kind: Pod
metadata:
  name: sd-trainer
  labels:
    app: sd-trainer
spec:
  imagePullSecrets:
    - name: cantor-registry-secret  # Replace with your secret name
  containers:
  - name: sd-trainer
    image: jcr.aac-cantor.com/docker-local/mlperf-sd:rocm-latest
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    volumeMounts:
    - name: sd-trainer-volume
      mountPath: /data
    resources:
      requests:
        memory: "64Gi"
        cpu: "32"
      limits:
        memory: "128Gi"
        cpu: "64"
  volumes:
  - name: sd-trainer-volume
    persistentVolumeClaim:
      claimName: efs-pvc